
#ifndef AARQ_H
#define AARQ_H 1

#define MECHA_NAME_SIZE 7
#define APP_CONTEXT_LEN 11
#define AARQ_AE_CALLING_QUALIFIER_LEN 508

typedef enum
{
    ACCEPTED,
    REJECTED_PERMANENT,
    REJECTED_TRANSIENT
} association_result_type;

typedef enum
{
    ACSE_USER_NULL,
    ACSE_NO_REASON_GIVEN_USER,
    ACSE_APP_CONTEXT_NAME_NOT_SUPPORTED,
    ACSE_AUTH_MECHA_NAME_NOT_RECOGNISED = 11,
    ACSE_AUTH_MECHA_NAME_REQUIRED,
    ACSE_AUTH_FAILURE,
    ACSE_AUTH_REQUIRED
} associated_source_diag_user_type;

typedef enum
{
    ACSE_PROVIDER_NULL,
    ACSE_NO_REASON_GIVEN_PROVIDER,
    ACSE_NO_COMMON_ACSE_VERSION
} associated_source_diag_provider_type;

typedef enum
{
    SVCERR_OTHER,
    SVCERR_DLMS_VER_TOOLOW,
    SVCERR_INCOMPATIBLE_CONFORMANCE,
    SVCERR_PDU_TOOSHORT,
    SVCERR_REFUSED_BY_VDE
} service_err_type;

typedef enum
{
    UINF_OK,
    UINF_DK_NOT_SUPPORTED,
    UINF_DLMS_VER_LOW,
    UINF_CONFORMANCE_NOT_SUPPORTED,
    UINF_CLIENT_RCV_LOW,
    UINF_ERROR
} user_info_rslt_type;

typedef enum
{
    AARQ_NULL,
    AARQ_OK,
    AARQ_PROTOCOL_VER_ERROR,
    AARQ_APP_CONTEXT_ERROR,
    AARQ_AUTH_ERROR,
    AARQ_UINF_ERROR,
    AARQ_UINF_DLMS_VER_LOW,
    AARQ_UINF_CONFORMANCE_NOT,
    AARQ_UINF_CLIENT_RCV_LOW,
    AARQ_IMPL_INF_NOT_SUPPORTED,
    AARQ_SERVICE_NOT,
    AARQ_ERROR,
    AARQ_UINF_DK_UNSUPPORT  // ctt3.1
} aarq_rslt_type;

#define APPCTXT_LN_NO_CIPHERING 1
#define APPCTXT_SN_NO_CIPHERING 2
#define APPCTXT_LN_CIPHERING 3
#define APPCTXT_SN_CIPHERING 4

#define AUTHMECH_LOWEST_LEVEL 0
#define AUTHMECH_LOW_LEVEL 1
#define AUTHMECH_HIGH_LEVEL 2
#define AUTHMECH_HIGH_GMAC 5
#define AUTHMECH_HIGH_ECDSA 7

enum
{
    CLASS_MASK = 0xC0,
    TYPE_MASK =
        0x20,  //< Bit 6 indicates if it is a Primitive (0) of Constructed (1)
    TAG_MASK = 0x1F,
    LEN_XTND = 0x80,
    LEN_MASK = 0x7F
};

enum tag_class
{
    TAG_UNIVERSAL = 0x00U,
    TAG_APPLICATION = 0x40U,
    TAG_CONTEXT_SPECIFIC = 0x80U,
    TAG_PRIVATE = 0xC0U
};

enum
{
    TAG_PRIMITIVE = 0U,
    TAG_CONSTRUCTED = TYPE_MASK
};

enum
{
    BER_TYPE_EOC = 0U,
    BER_TYPE_BOOLEAN = 1U,
    BER_TYPE_INTEGER = 2U,
    BER_TYPE_BIT_STRING = 3U,
    BER_TYPE_OCTET_STRING = 4U,
    BER_TYPE_NULL = 5U,
    BER_TYPE_OBJECT_IDENTIFIER = 6U,
};

#define ASSO_AARQ \
    TAG_APPLICATION + TAG_CONSTRUCTED + 0U  ///< Application number 0 = 0x60
#define ASSO_AARE \
    TAG_APPLICATION + TAG_CONSTRUCTED + 1U  ///< Application number 1 = 0x61
#define ASSO_RLRQ \
    TAG_APPLICATION + TAG_CONSTRUCTED + 2U  ///< Application number 2 = 0x62
#define ASSO_RLRE \
    TAG_APPLICATION + TAG_CONSTRUCTED + 3U  ///< Application number 3s = 0x63
#define ASSO_PROTO_VER TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE  // 0x80
#define ASSO_APP_CONTEXT_NAME \
    TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 1U  // 0xA1
// AARQ tags
#define ASSO_CALLED_AP_TITLE \
    TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 2U  // 0xA2
#define ASSO_CALLED_AE_QUALIFIER TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 3U
#define ASSO_CALLED_AP_INVOC_ID TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 4U
#define ASSO_CALLED_AE_INVOC_ID TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 5U
#define ASSO_CALLING_AP_TITLE \
    TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 6U  // 0xA6
#define ASSO_CALLING_AE_QUALIFIER \
    TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 7U  // 0xA7
#define ASSO_CALLING_AP_INVOC_ID TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 8U
#define ASSO_CALLING_AE_INVOC_ID TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 9U
#define ASSO_SENDER_ACSE_REQU \
    TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE + 10U  // 0x8A
#define ASSO_REQ_MECHANISM_NAME \
    TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE + 11U  // 0x8B
#define ASSO_CALLING_AUTH_VALUE \
    TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 12U  // 0xAC
#define ASSO_IMPLEMENTATION_INFO TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 29U
#define ASSO_USER_INFORMATION \
    TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 30U  // 0xBE
// AARE tags
#define ASSO_RESP_AUTH_VALUE \
    TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 10U  // 0xAA
#define ASSO_RESP_MECHANISM_NAME \
    TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE + 9U  // 0x89
#define ASSO_RESPONDER_ACSE_REQ \
    TAG_CONTEXT_SPECIFIC + TAG_PRIMITIVE + 8U  // 0x88
#define ASSO_RESP_AE_QUALIFIER \
    TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 5U                         // 0xA5
#define ASSO_RESP_AP_TITLE TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 4U  // 0xA4
#define ASSO_RESULT_FIELD TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 2U   // 0xA2
#define ASSO_RESULT_SRC_DIAG \
    TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 3U  // 0xA3
#define ASSO_RESULT_SERVICE_USER \
    TAG_CONTEXT_SPECIFIC + TAG_CONSTRUCTED + 1U  // 0xA1

extern uint8_t mecha_name_asso3[MECHA_NAME_SIZE];
extern uint8_t app_context_name_asso3[APP_CONTEXT_LEN];
extern uint8_t calling_ae_qualifier[AARQ_AE_CALLING_QUALIFIER_LEN];

aarq_rslt_type appl_AARQ_proc(int idx);
aarq_rslt_type appl_AARQ_asso3_proc(int idx);
int appl_fill_context_name(uint8_t *buf);
int appl_fill_mecha_name(uint8_t *buf);
int appl_fill_mecha_name_noauth(uint8_t *buf);

#endif
