#ifndef __VERIFIER_H__
#define __VERIFIER_H__

#define DEVICE_SIGNATURE_MAGIC_ADDRESS		0x2E000
#define DEVICE_SIGNATURE_MAGIC_SIZE			4

#define DEVICE_ISSUER_PUBKEY_ADDRESS		(DEVICE_SIGNATURE_MAGIC_ADDRESS + DEVICE_SIGNATURE_MAGIC_SIZE)
#define DEVICE_ISSUER_PUBKEY_SIZE			64

#define DEVICE_SIGNATURE_ADDRESS			(DEVICE_ISSUER_PUBKEY_ADDRESS + DEVICE_ISSUER_PUBKEY_SIZE)
#define DEVICE_SIGNATURE_SIZE				64

#define DEVICE_SIGNATURE_MAGIC				0x44535631		// "DSV1" ==> DEVICE SIGNATURE V1

int verify_device_signature();
	
#endif
